### ISSUE TITLE
 translator.langs raise Yandex::ApiError

### ISSUE THREAD

**Issue by lemboy** [aegorov/yandex-translator#7]
It's OK:
```
> translator = Yandex::Translator.new('trnsl.1.1._xxxx') 
=> #<Yandex::Translator:0xbb7dea04 @api_key="trnsl.1.1._xxxx">
```

It's OK too:
```
> translator.detect 'Hello, world!'
=> "en"
```

But it's raise error:
```
>  translator.langs
Yandex::ApiError: Yandex::ApiError
```
**Edit.**
At last case HTTParty::Response has not ['code'] field.

**Comment by aegorov** [comment]
@lemboy Thank you for issue. Yes, it's looks like Yandex api did not return 200 code on getLands method now. I fix it https://github.com/aegorov/yandex-translator/commit/ec238601b51f34977799a6cf261ecff885487c86
